apiVersion: v1
kind: Service
metadata:
  name: microservice-service
spec:
  type: LoadBalancer
  selector:
    app: microservice-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
