apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: 150553123024.dkr.ecr.eu-central-1.amazonaws.com/yevhen.bulatnikov/eureka-server:latest
          ports:
            - containerPort: 8761
